version: "3.7"
networks:
  dev_default:
    external: true
services:
  focus:
    depends_on:
      - blaze
    image: samply/focus:main
    environment:
      API_KEY: "App1Secret"
      BEAM_APP_ID_LONG: focus.proxy2.broker
      BLAZE_URL: "http://blaze:8080/fhir/"
      BEAM_PROXY_URL: http://proxy2:8082
      RETRY_COUNT: 30
      OBFUSCATE: "no"
    networks:
      - default
      - dev_default

  blaze:
    image: samply/blaze
    volumes:
      - "blaze-data:/app/data"
    networks:
      - default

  test-data-loader:
    image: samply/test-data-loader
    environment:
      FHIR_STORE_URL: "http://blaze:8080/fhir"
      PATIENT_COUNT: "2000"
    command: sh -c "sleep 60 && /app/run.sh"
    networks:
      - default

volumes:
  blaze-data:
