version: "3.7"
services:
  vault:
    image: hashicorp/vault
    ports:
      - 127.0.0.1:8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    volumes:
      - ./pki:/pki
    networks:
      - default
  broker:
    depends_on: [vault]
    image: samply/beam-broker:develop
    ports:
      - 8080:8080
      - 8090:8090
    environment:
      BROKER_URL: ${BROKER_URL}
      PKI_ADDRESS: http://vault:8200
      no_proxy: vault
      NO_PROXY: vault
      PRIVKEY_FILE: /run/secrets/dummy.pem
      BIND_ADDR: 0.0.0.0:8080
      MONITORING_API_KEY: ${BROKER_MONITORING_KEY}
      RUST_LOG: ${RUST_LOG}
      ALL_PROXY: http://mitmproxy:8080
    secrets:
      - pki.secret
      - dummy.pem
      - root.crt.pem
  mitmproxy:
    image: mitmproxy/mitmproxy
    stop_signal: SIGKILL
    command: mitmweb --web-host 0.0.0.0 --web-port 9090
    ports:
      - 9090:9090
  proxy1:
    depends_on: [broker]
    image: samply/beam-proxy:develop
    ports:
      - 8081:8081
    environment:
      BROKER_URL: ${BROKER_URL}
      PROXY_ID: ${PROXY1_ID}
      APP_app1_KEY: ${APP_KEY}
      APP_app2_KEY: ${APP_KEY}
      PRIVKEY_FILE: /run/secrets/proxy1.pem
      BIND_ADDR: 0.0.0.0:8081
      RUST_LOG: ${RUST_LOG}
      ALL_PROXY: http://mitmproxy:8080
    secrets:
      - proxy1.pem
      - root.crt.pem
  proxy2:
    depends_on: [broker]
    image: samply/beam-proxy:develop
    ports:
      - 8082:8082
    environment:
      BROKER_URL: ${BROKER_URL}
      PROXY_ID: ${PROXY2_ID}
      APP_app1_KEY: ${APP_KEY}
      APP_app2_KEY: ${APP_KEY}
      PRIVKEY_FILE: /run/secrets/proxy2.pem
      BIND_ADDR: 0.0.0.0:8082
      RUST_LOG: ${RUST_LOG}
      ALL_PROXY: http://mitmproxy:8080
    secrets:
      - proxy2.pem
      - root.crt.pem
  focus:
    depends_on:
      - proxy1
      - blaze
    build:
      context: ../
      dockerfile: Dockerfile
    image: samply/focus:${TAG}
    environment:
      API_KEY: ${APP_KEY}
      BEAM_APP_ID_LONG: app1.${PROXY1_ID}
      BLAZE_URL: "http://blaze:8080/fhir/"
      BEAM_PROXY_URL: http://proxy1:8081
      RETRY_COUNT: 30
      OBFUSCATE: "no"
  blaze:
    image: samply/blaze
    volumes:
      - "blaze-data:/app/data"
secrets:
  pki.secret:
    file: ./pki/pki.secret
  proxy1.pem:
    file: ./pki/${PROXY1_ID_SHORT}.priv.pem
  proxy2.pem:
    file: ./pki/${PROXY2_ID_SHORT}.priv.pem
  dummy.pem:
    file: ./pki/dummy.priv.pem
  root.crt.pem:
    file: ./pki/root.crt.pem

volumes:
  blaze-data:
