name: Build with rust and docker

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build-with-samply:
    uses: samply/github-workflows/.github/workflows/rust.yml@main
    with:
      image-prefix: "samply/"
      components: '[ "focus" ]'
      #architectures: '[ "amd64", "arm64" ]'
      #profile: debug
      test-via-script: false
      features: '[ "bbmri", "dktk", "" ]'
      push-to: ${{'dockerhub'}}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
