name: Build with rust and docker

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build-with-samply:
    uses: samply/github-workflows/.github/workflows/rust.yml@faster
    with:
      image-prefix: "samply/"
      components: '[ "focus" ]'
      architectures: '[ "amd64", "arm64" ]'
      #profile: debug
      test-via-script: false
      features: '[ "bbmri", "dktk", "query-sql", "" ]'
      push-to: ${{ (github.ref_protected == true || github.event_name == 'workflow_dispatch') && 'dockerhub' || 'ghcr' }}
      cargo-fmt-check: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
